"""add dibuat_oleh to ruang_video

Revision ID: 66753b50464e
Revises: ca519862a288
Create Date: 2025-07-01 14:39:35.227179

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "66753b50464e"
down_revision = "ca519862a288"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('favorite_karya')
    with op.batch_alter_table("ruang_video", schema=None) as batch_op:
        batch_op.alter_column(
            "dibuat_oleh", existing_type=mysql.VARCHAR(length=100), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ruang_video", schema=None) as batch_op:
        batch_op.alter_column(
            "dibuat_oleh", existing_type=mysql.VARCHAR(length=100), nullable=True
        )

    op.create_table(
        "favorite_karya",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "karya_seni_id", mysql.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("user_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            mysql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["karya_seni_id"],
            ["karya_seni.id"],
            name=op.f("favorite_karya_ibfk_1"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("favorite_karya_ibfk_2"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
