"""add like_count

Revision ID: 838657464179
Revises: 66753b50464e
Create Date: 2025-07-06 15:19:35.410663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '838657464179'
down_revision = '66753b50464e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('karya_seni', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('karya_seni', schema=None) as batch_op:
        batch_op.drop_column('like_count')

    # ### end Alembic commands ###
